//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyalKeyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardDescription
    {
        public int RewardDescriptionID { get; set; }
        public int RewardID { get; set; }
        public string Description { get; set; }
        public decimal Value { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Reward Reward { get; set; }
    }
}
