//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyalKeyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RewardDetail()
        {
            this.Rewards = new HashSet<Reward>();
        }
    
        public int RewardDetailID { get; set; }
        public int RewardTypeID { get; set; }
        public Nullable<decimal> Max { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reward> Rewards { get; set; }
        public virtual RewardType RewardType { get; set; }
    }
}
